name: Tests on Ubuntu

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ninja
      run: sudo apt update && sudo apt install ninja-build
      
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_CXX_COMPILER=g++-13 -DCMAKE_C_COMPILER=gcc-13 -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all -j $(nproc)

    - name: Run CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Test server and client
      working-directory: ${{github.workspace}}
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
        poetry shell
        ./test_cmds.py --server ${{github.workspace}}/build/server --client ${{github.workspace}}/build/client

